### ISSUE TITLE
Invalid octet 0x80 in OID enoding

### ISSUE THREAD

**Issue by scotloach** [etingof/pysnmp#119]
I'm getting this error thrown here:
https://github.com/etingof/pysnmp/blob/0aa119f1aaa9dee756aeaf65cd77c72581adcf36/pysnmp/proto/rfc3412.py#L348

The response is from a real device, and is accepted fine by net-snmp and is decoded by tcpdump.  Here is a packet capture of the response PDU.
```
12:59:42.641343 IP 10.102.2.18.161 > 209.251.86.58.50921:  GetResponse(41) 
.1.3.6.1.4.1.32584.1.8.5.1.0=12
        0x0000:  4500 0058 cdd9 4000 7e11 fa0d 0a66 0212  E..X..@.~....f..      
        0x0010:  d1fb 563a 00a1 c6e9 0044 f02c 3082 0038  ..V:.....D.,0..8      
        0x0020:  0201 0004 0670 7562 6c69 63a2 8200 2902  .....public...).      
        0x0030:  0475 f671 9902 0100 0201 0030 8200 1930  .u.q.......0...0      
        0x0040:  8200 1506 8200 0e2b 0601 0401 8081 fe48  .......+.......H      
        0x0050:  0108 0501 0002 010c                      ........    
```

**Comment by etingof** [comment]
Looks like parsing error. Can you see the original exception? If you enable pysnmp debugging and retry that request:

    from pysnmp import debug
    debug.setLogger(debug.Debug('all'))

It should get logged here:

     debug.logger & debug.flagMP and debug.logger('receiveMessage: %s' % (sys.exc_info()[1],))

**Comment by scotloach** [comment]
yes

2017-12-20 15:18:24,106 pysnmp: receiveMessage: msgVersion 1, msg decoded
2017-12-20 15:18:24,106 pysnmp: receiveMessage: msgVersion 1, msg decoded
2017-12-20 15:18:24,107 pysnmp: receiveMessage: Invalid octet 0x80 in OID encoding
2017-12-20 15:18:24,107 pysnmp: receiveMessage: Invalid octet 0x80 in OID encoding

**Comment by scotloach** [comment]
Here is the full traceback:
```Exception in callback AbstractTransportDispatcher._cbFun(<pysnmp.carri...x7f3e5f0b6b70>, ('10.102.2.18', 161), b'0\x82\x008\...0\x02\x01\x0e')
handle: <Handle AbstractTransportDispatcher._cbFun(<pysnmp.carri...x7f3e5f0b6b70>, ('10.102.2.18', 161), b'0\x82\x008\...0\x02\x01\x0e')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pysnmp/proto/rfc3412.py", line 331, in receiveMessage
    snmpEngine, transportDomain, transportAddress, wholeMsg
  File "/usr/lib/python3.5/site-packages/pysnmp/proto/mpmod/rfc2576.py", line 250, in prepareDataElements
    msg, restOfWholeMsg = decoder.decode(wholeMsg, asn1Spec=self._snmpMsgSpec)
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 497, in valueDecoder
    component, head = decodeFun(head, asn1Spec, **options)
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 687, in valueDecoder
    tagSet, length, state, **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 497, in valueDecoder
    component, head = decodeFun(head, asn1Spec, **options)
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 524, in valueDecoder
    component, head = decodeFun(head, asn1Spec, **options)
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 497, in valueDecoder
    component, head = decodeFun(head, asn1Spec, **options)
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/lib/python3.5/site-packages/pyasn1/codec/ber/decoder.py", line 301, in valueDecoder
    raise error.PyAsn1Error('Invalid octet 0x80 in OID encoding')
pyasn1.error.PyAsn1Error: Invalid octet 0x80 in OID encoding
```

**Comment by scotloach** [comment]
That error is thrown from code with this comment: ```
                # ASN.1 spec forbids leading zeros (0x80) in OID
                # encoding, tolerating it opens a vulnerability. See
                # http://www.cosic.esat.kuleuven.be/publications/article-1432.pdf
                # page 7
```

Well maybe so, but obviously I have some device that's sending that anyway.  Maybe a config switch to allow this?

**Comment by scotloach** [comment]
And fwiw, here's how Wireshark decodes it.  I am not a ASN.1 expert so I will leave that to others.

![screenshot from 2017-12-28 10-17-25](https://user-images.githubusercontent.com/11753520/34414645-742b8e80-ebb8-11e7-9075-319126c61d54.png)

**Comment by scotloach** [comment]
@etingof do you have any thoughts on this?  It's a pretty big blocker for using this SNMP library with some devices.
