### ISSUE TITLE
Problems forming instance-identifier for TCP-MIB::tcpConnectionState #54 reoccurred

### ISSUE THREAD

**Issue by whpark70** [etingof/pysnmp#148]
I'm newbie for pysnmp.

My test env. is belows.
**python ver.: 3.6.3
os: windows 10

pip list
pysmi (0.3.0)
pysnmp (5.0.0)
pysnmp-mibs (0.1.6)
pyasn1 (0.4.2)**

test code is same ( http://pysnmp.sourceforge.net/docs/pysnmp-hlapi-tutorial.html)
from pysnmp.hlapi import *

g = getCmd( SnmpEngine(),
			CommunityData('public'),
			UdpTransportTarget(('demo.snmplabs.com', 161)),
			ContextData(),
			ObjectType(ObjectIdentity('TCP-MIB', 'tcpConnectionState',
	'ipv4', '195.218.254.105', 41511,
	'ipv4', '194.67.1.250', 993))
	)

next(g)

the  error is
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: b'195.218.254.105'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 497, in _testValue
    constraint(value, idx)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4> failed at: ValueConstraintError(b'195.218.254.105',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\base.py", line 242, in __init__
    self.subtypeSpec(value)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ConstraintsIntersection object at 0x211768ca5f8 consts <ValueSizeConstraint object at 0x21175b05b70 consts 0, 65535>, <ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4> failed at: ValueConstraintError(b'195.218.254.105',)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\smi\rfc1902.py", line 505, in resolveWithMib
  File "<string>", line 1271, in getInstIdFromIndices
  File "<string>", line 1052, in getAsName
  File "<string>", line 93, in cloneAsName
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\proto\rfc1902.py", line 202, in clone
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\base.py", line 349, in clone
    return self.__class__(value, **initilaizers)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\univ.py", line 819, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "D:\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\base.py", line 246, in __init__
    raise exType('%s at %s' % (exValue, self.__class__.__name__))
pyasn1.type.error.ValueConstraintError: <ConstraintsIntersection object at 0x211768ca5f8 consts <ValueSizeConstraint object at 0x21175b05b70 consts 0, 65535>, <ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4> failed at: ValueConstraintError(b'195.218.254.105',)",) at InetAddressIPv4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getcmd_0.py", line 12, in <module>
    next(g)
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\hlapi\asyncore\sync\cmdgen.py", line 111, in getCmd
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\hlapi\asyncore\cmdgen.py", line 129, in getCmd
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\hlapi\varbinds.py", line 39, in makeVarBinds
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\smi\rfc1902.py", line 847, in resolveWithMib
  File "D:\Python36\lib\site-packages\pysnmp-5.0.0-py3.6.egg\pysnmp\smi\rfc1902.py", line 510, in resolveWithMib
pysnmp.smi.error.SmiError: Instance index ('ipv4', '195.218.254.105', 41511, 'ipv4', '194.67.1.250', 993) to OID convertion failure at object 'tcpConnectionState': <ConstraintsIntersection object at 0x211768ca5f8 consts <ValueSizeConstraint object at 0x21175b05b70 consts 0, 65535>, <ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x211768ca5c0 consts 4, 4> failed at: ValueConstraintError(b'195.218.254.105',)",) at InetAddressIPv4

**Comment by etingof** [comment]
Thanks for the heads up!

I hope this is fixed in master now. Please, try it out and let me know if it works for you.

**Comment by whpark70** [comment]
Fixed. Thanks ^^

**Comment by etingof** [comment]
I've reworked the patch a bit, it's also in master.
