### ISSUE TITLE
TypeError: clone() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by igopan** [etingof/pysnmp#185]
Occasionally we get the following error when trying to access one of the devices via pysnmp:

Traceback (most recent call last):
  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/temp.py", line 87, in get_interface_state
    cmdgen.MibVariable("IF-MIB", "ifAdminStatus", interface)
  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 183, in getCmd
    **kwargs):
  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 113, in getCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
PySnmpError: poll error: Traceback (most recent call last):
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib64/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
;  File "/usr/lib64/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
;  File "/usr/lib64/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib64/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pysnmp/proto/api/verdec.py", line 17, in decodeMessageVersion
    recursiveFlag=False, substrateFun=lambda a, b, c: (a, b[:c])
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1293, in __call__
    **options
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 65, in valueDecoder
    self._createComponent(asn1Spec, tagSet, '', **options),
;  File "/temp/our_lib/v1.1.0/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 53, in _createComponent
    return asn1Spec.clone(value)
;TypeError: clone() takes exactly 1 argument (2 given)

However it is impossible to work out what the problem is, because it seems that the original error is hidden away and the next time (in ~1 minute) when we execute the command again the error disappears.

The following command is being executed:
        error, _, _, var_binds = CMD_GEN.getCmd(
            cmdgen.CommunityData(community),
            cmdgen.UdpTransportTarget((device, DEFAULT_SNMP_PORT)),
            cmdgen.MibVariable("IF-MIB", "ifAdminStatus", interface)
        )

**Comment by etingof** [comment]
This may have something to do with the malformed SNMP response occasionally coming to pysnmp...

To track this down I'd suggest either of:

* enabling `pyasn1` debugging

    from pyasn1 import debug

    debug.setLogger(debug.Debug('decoder'))

* `tcpdump -w dump.pcap -s0 port 161` and match incoming packet with pysnmp traceback by time

If you could share some data with me, that would simplify tracking this down.

Also, which pyasn1/pysnmp is that? It's better to upgrade to the latest released versions.

**Comment by igopan** [comment]
Thank you for suggestions. It might be not easy to modify the source of the script on our end, will see what we can do on our end.

Oh, sorry, meant to specify the versions: pynsnmp=4.4.2 and pyasn1=0.4.4

**Comment by etingof** [comment]
I do not see related changes in the later versions of pysnmp. And pyasn1 is up to date. So it looks like a bug in either of these packages, more likely in pyasn1.

If it's hard to modify the source, I can offer you a quick fix that would enable debugging my way of an environment variable.

Or just capturing SNMP traffic off the network might work out for troubleshooting purposes.

**Comment by igopan** [comment]
We will enable tcpdump and try to capture the malformed response. However it doesn't happen often, so we might need to wait a couple of months. Will update the ticket as soon as we get more info.

**Comment by wisererik** [comment]
Hi @etingof is this issuse fixed? I also encountered this problem, it caused the snmp process to exit.

**Comment by lextm** [comment]
@wisererik If you read the discussion carefully, you can see you are supposed to enable debugging like the steps indicated to locate the possible malformed data.

You should ask the faulty SNMP device vendor to patch, if such malformed data are located. On PySNMP side there can be nothing to fix.
