### ISSUE TITLE
Integer32 object has no attribute 'asNumbers'.

### ISSUE THREAD

**Issue by gejr** [etingof/pysnmp#206]
I realize this might not be the best issue report ever made, but I'm afraid I have little to work with here. At one point one of our nodes' snmp-agents crashed with the following stacktrace. I don't know what to include except this, and that this happened seemingly randomly one day on a server with ubuntu xenial and pysnmp 4.4.4 installed.

The nodes gets fed data from an open_vswitch database, and there's a slew of company-specific mibs to expose them over SNMP. As far as I can see the error happens during a ReadGetNext-operation somewhere.

I have as far as i know no other logs, and unfortunately no wireshark output. Is there any common mistakes/pitfalls I may have made to cause this error? Or any tips on how I can make sure to get more detailed logs in case it happens again? 

Regards

> `Traceback (most recent call last):
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
>     use_poll=True, map=self.__sockMap, count=1)
>   File "/usr/lib/python3.5/asyncore.py", line 207, in loop
>     poll_fun(timeout, map)
>   File "/usr/lib/python3.5/asyncore.py", line 188, in poll2
>     readwrite(obj, flags)
>   File "/usr/lib/python3.5/asyncore.py", line 123, in readwrite
>     obj.handle_error()
>   File "/usr/lib/python3.5/asyncore.py", line 108, in readwrite
>     obj.handle_read_event()
>   File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
>     self.handle_read()
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
>     self._cbFun(self, transportAddress, incomingMessage)
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/base.py", line 70, in _cbFun
>     self, transportDomain, transportAddress, incomingMessage
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
>     self, transportDomain, transportAddress, wholeMsg
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/proto/rfc3412.py", line 433, in receiveMessage
>     PDU, maxSizeResponseScopedPDU, stateReference)
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 140, in processPdu
>     (self.__verifyAccess, snmpEngine))
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 308, in handleMgmtOperation
>     rspVarBinds.extend(mgmtFun(varBinds, (acFun, acCtx)))
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/smi/instrum.py", line 253, in readNextVars
>     return self.flipFlopFsm(self.fsmReadNextVar, varBinds, acInfo)
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/smi/instrum.py", line 221, in flipFlopFsm
>     rval = f(tuple(name), val, idx, acInfo)
>   File "<string>", line 516, in readGetNext
>   File "<string>", line 516, in readGetNext
>   File "<string>", line 619, in readGetNext
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 201, in __verifyAccess
>     securityLevel, viewType, contextName, name
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/proto/acmod/rfc3415.py", line 109, in isAccessAllowed
>     for c in vacmViewTreeFamilyMask.syntax.asNumbers():
> AttributeError: 'Integer32' object has no attribute 'asNumbers'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./src/snmpd.py", line 695, in <module>
>     agent.serve(event)
>   File "./src/snmpd.py", line 635, in serve
>     self._snmpEngine.transportDispatcher.runDispatcher()
>   File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
>     raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
> pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
>     use_poll=True, map=self.__sockMap, count=1)
> ;  File "/usr/lib/python3.5/asyncore.py", line 207, in loop
>     poll_fun(timeout, map)
> ;  File "/usr/lib/python3.5/asyncore.py", line 188, in poll2
>     readwrite(obj, flags)
> ;  File "/usr/lib/python3.5/asyncore.py", line 123, in readwrite
>     obj.handle_error()
> ;  File "/usr/lib/python3.5/asyncore.py", line 108, in readwrite
>     obj.handle_read_event()
> ;  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
>     self.handle_read()
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
>     self._cbFun(self, transportAddress, incomingMessage)
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/carrier/base.py", line 70, in _cbFun
>     self, transportDomain, transportAddress, incomingMessage
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
>     self, transportDomain, transportAddress, wholeMsg
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/proto/rfc3412.py", line 433, in receiveMessage
>     PDU, maxSizeResponseScopedPDU, stateReference)
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 140, in processPdu
>     (self.__verifyAccess, snmpEngine))
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 308, in handleMgmtOperation
>     rspVarBinds.extend(mgmtFun(varBinds, (acFun, acCtx)))
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/smi/instrum.py", line 253, in readNextVars
>     return self.flipFlopFsm(self.fsmReadNextVar, varBinds, acInfo)
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/smi/instrum.py", line 221, in flipFlopFsm
>     rval = f(tuple(name), val, idx, acInfo)
> ;  File "<string>", line 516, in readGetNext
> ;  File "<string>", line 516, in readGetNext
> ;  File "<string>", line 619, in readGetNext
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/entity/rfc3413/cmdrsp.py", line 201, in __verifyAccess
>     securityLevel, viewType, contextName, name
> ;  File "/opt/snmp-agent/0.0.21/src/pysnmp/proto/acmod/rfc3415.py", line 109, in isAccessAllowed
>     for c in vacmViewTreeFamilyMask.syntax.asNumbers():
> ;AttributeError: 'Integer32' object has no attribute 'asNumbers'
> `

**Comment by lextm** [comment]
This seems to be a bug of the old release you used, but fixed in later releases. So, it can be closed.
