### ISSUE TITLE
objectIdentity object not properly initialized

### ISSUE THREAD

**Issue by CharlesJu1** [etingof/pysnmp#223]
I installed pysnmp and tried examples from the website snmplabs.com.  I got the following error:

```
cju@ubuntu-16:~$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from pysnmp.hlapi import *
>>> x = ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)
>>> 
>>> tuple(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cju/.local/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 606, in __len__
    raise SmiError('%s object not properly initialized' % self.__class__.__name__)
pysnmp.smi.error.SmiError: ObjectIdentity object not properly initialized
```

However, I could run the following example code ok.

```
>>> errorIndication, errorStatus, errorIndex, varBinds = next(
...     getCmd(SnmpEngine(),
...            CommunityData('public', mpModel=0),
...            UdpTransportTarget(('demo.snmplabs.com', 161)),
...            ContextData(),
...            ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
... )
>>> 
>>> if errorIndication:
...     print(errorIndication)
... elif errorStatus:
...     print('%s at %s' % (errorStatus.prettyPrint(),
...                         errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
... else:
...     for varBind in varBinds:
...         print(' = '.join([x.prettyPrint() for x in varBind]))
... 
SNMPv2-MIB::sysDescr.0 = Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686
```

**Comment by etingof** [comment]
That's right, `ObjectIdentity` works lazily. If you want it to get resolved against a MIB you need to explicitly call `.resolveWithMib()` as [noted in the docs](http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity.resolveWithMib).

You will also need the `MibViewController` object, just follow [this example](http://snmplabs.com/pysnmp/examples/smi/manager/browsing-mib-tree.html#mib-objects-to-pdu-var-binds) - the first three lines of that script seem to do what you are trying to do.

**Comment by CharlesJu1** [comment]
Thanks etingof. It works following your reply. I now understand that pysnmp needs mibs to be installed as a python module named like mibname.py. Is there a command to install some other mibs besides the built-in mibs installed along with pysnmp? How to list what mibs are already installed?

**Comment by etingof** [comment]
No *need* to compile MIB files into Python. If you [configure the source of ASN.1 MIBs](http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity.addAsn1MibSource), the translation would happen behind the scene.

But you can also compile ASN.1 MIB(s) into Python with [mibdump tool](
http://snmplabs.com/pysmi/mibdump.html).

**Comment by CharlesJu1** [comment]
If I configure the source of ASN.1 MIBs, it will download and translate the ASN.1 MIB on the fly. That may take some more time than a local copy of MIB. I noticed that SNMPv2-MIB.py exists both in ~/.pysnmp/mibs and ~/.local/lib/python3.5/site-packages/pysnmp/smi/mibs. However, IF-MIB.py only exists in ~/.pysnmp/mibs folder. Why is that?

**Comment by etingof** [comment]
> If I configure the source of ASN.1 MIBs, it will download and translate the ASN.1 MIB on the fly. That may take some more time than a local copy of MIB. 

This downloading and translation happens just once and results in caching the translated module in `~/.pysnmp/mibs/`. Once cached files are there, no more translation should occur.

> I noticed that SNMPv2-MIB.py exists both in ~/.pysnmp/mibs and ~/.local/lib/python3.5/site-packages/pysnmp/smi/mibs. However, IF-MIB.py only exists in ~/.pysnmp/mibs folder. Why is that?

I am guessing that you played with MIB compiler at the moment when pysnmp was not available so the compiler tried to translate `SNMPv2-MIB.py`. Normally, you should use `SNMPv2-MIB.py` shipped with pysnmp because this is one of the core MIBs that are not fully translatable because they require some custom code on top of automatically generated code.

**Comment by CharlesJu1** [comment]
Thanks etingof. When using mibdump.py to generate MIBs in pysnmp format, can I generate mib indices? Where is the indices file and how it is used?

**Comment by frsoto** [comment]
> MibViewController

Hi.
the link no longer exists
I have the same doubt

Regards..

**Comment by lextm** [comment]
@frsoto You can read #429 for more details. The domain snmplabs.com was lost so any connection to it today is risky.
