### ISSUE TITLE
MIB OLD-CISCO-CHASSIS-MIB, OID cardType throwing exception

### ISSUE THREAD

**Issue by asw001** [etingof/pysnmp#227]
Using Python 2.6.6,  pysnmp-4.4.6, pysmi-0.3.2, OIDs values are returned with no issue.
Using Python 2.7.5, pysnmp-4.4.6, pysmi-0.3.2, the stack trace below is generated.

I am thinking this needs to be truncated as it is quite long, attachment don't take.

File "/apps/run_snmp_discovery.py", line 43, in <module>
print(dc.snmpwalk(cli.mib_to_oid, cli.timeout, cli.retries, cli.invert, cli.lexmode, cli.verbose))
File "/apps/DiscoverSnmpClient.py", line 138, in snmpwalk
ObjectType(ObjectIdentity(mib, oid)),lexicographicMode=lexicographic_mode):
File "/usr/lib/python2.7/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 362, in nextCmd
snmpEngine.transportDispatcher.runDispatcher()
File "/usr/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
use_poll=True, map=self.__sockMap, count=1)
File "/usr/lib64/python2.7/asyncore.py", line 220, in loop
poll_fun(timeout, map)
File "/usr/lib64/python2.7/asyncore.py", line 201, in poll2
readwrite(obj, flags)
File "/usr/lib64/python2.7/asyncore.py", line 123, in readwrite
obj.handle_error()
File "/usr/lib64/python2.7/asyncore.py", line 108, in readwrite
obj.handle_read_event()
File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
self.handle_read()
File "/usr/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
self._cbFun(self, transportAddress, incomingMessage)
File "/usr/lib/python2.7/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
self, transportDomain, transportAddress, incomingMessage
File "/usr/lib/python2.7/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
self, transportDomain, transportAddress, wholeMsg
File "/usr/lib/python2.7/site-packages/pysnmp/proto/rfc3412.py", line 486, in receiveMessage
cachedParams['cbCtx'])
File "/usr/lib/python2.7/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 152, in processResponsePdu
cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
File "/usr/lib/python2.7/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 303, in processResponseVarBinds
varBindTable, cbCtx):
File "/usr/lib/python2.7/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 343, in __cbFun
varBindTable],
File "/usr/lib/python2.7/site-packages/pysnmp/hlapi/varbinds.py", line 46, in unmakeVarBinds
varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
File "/usr/lib/python2.7/site-packages/pysnmp/smi/rfc1902.py", line 871, in resolveWithMib
sys.exc_info()[1]))
;SmiError: MIB object 'OLD-CISCO-CHASSIS-MIB::cardType.1' having type 'Integer32' failed to cast value <Integer value object at 0x34769d0 subtypeSpec <ConstraintsIntersection object at 0x248d610 consts <ValueRangeConstraint object at 0x248d5d0 consts -2147483648, 2147483647>> tagSet <TagSet object at 0x2406750 tags 0:0:2> payload [1257]>: <ConstraintsIntersection object at 0x31e4290 consts <ValueRangeConstraint object at 0x248d5d0 consts -2147483648, 2147483647>, <ConstraintsUnion object at 0x31e4210 consts <SingleValueConstraint object at 0x31e4090 consts 1, 2, 3, 4

**Comment by asw001** [comment]
I tried again with Python3 (3.4). Essentially the same error, however this stands out:

failed for "1257"\',)',) at Integer32
caused by <class 'pysnmp.smi.error.SmiError'>: MIB object 'OLD-CISCO-CHASSIS-MIB::cardType.1' having type 'Integer32' failed to cast value <Integer value object at 0x7f9c87a49cf8 tagSet <TagSet object at 0x7f9c8f07fac8 tags 0:0:2> subtyp                                  eSpec <ConstraintsIntersection object at 0x7f9c8f2e4400 consts <ValueRangeConstraint object at 0x7f9c8f2e4358 consts -2147483648, 2147483647>> payload [1257]>: <ConstraintsIntersection object at 0x7f9c87f6e208 consts <ValueRangeConstrain                                  t object at 0x7f9c8f2e4358 consts -2147483648, 2147483647>, <ConstraintsUnion object at 0x7f9c87f6e898 consts <SingleValueConstraint object at 0x7f9c87f65748 consts 1, 

The MIB defines that value type as 'INTEGER', 

snmpwalk -c XXXX -v 2c 1.1.1.1 OLD-CISCO-CHASSIS-MIB::cardType
OLD-CISCO-CHASSIS-MIB::cardType.1 = INTEGER: 1257
OLD-CISCO-CHASSIS-MIB::cardType.2 = INTEGER: 4379
OLD-CISCO-CHASSIS-MIB::cardType.3 = INTEGER: 4374
OLD-CISCO-CHASSIS-MIB::cardType.4 = INTEGER: 4374
OLD-CISCO-CHASSIS-MIB::cardType.7 = INTEGER: 4756
OLD-CISCO-CHASSIS-MIB::cardType.8 = INTEGER: 4756

I understand INTEGER and INTEGER32 to be inter operable except when considering ranged restrictions, i.e. a bit isn't allocated for the sign.

**Comment by asw001** [comment]
non-issue. the MIB was out of date!

**Comment by etingof** [comment]
Awesome! I've just been looking at this. Sorry for it has taken so long...
