### ISSUE TITLE
Excessive instance identifier sub-OIDs left at MibTableRow

### ISSUE THREAD

**Issue by cissuppandi** [etingof/pysnmp#266]
Hi etingof,
Good Day.
I have tried to load a custom mib and did a snmp walk. but I am getting the below mentioned error.I have parse the mib file through the mibdump.py and format as pysnmp. I have tried the above solution mentioned by you but unfortunately it didn't help. I will be highly obliged if you can provide some more solution for the above issue.
***********************ERROR*****************************
AMIT-PDU-MIB::pduNamePlateTableSize.0 = 2
AMIT-PDU-MIB::pduNamePlateIndex.1 = 1
AMIT-PDU-MIB::pduNamePlateIndex.2 = 2
AMIT-PDU-MIB::pduNamePlateName.1 = 
AMIT-PDU-MIB::pduNamePlateName.2 = 
AMIT-PDU-MIB::pduNamePlateLocation.1 = 
AMIT-PDU-MIB::pduNamePlateLocation.2 = 
Traceback (most recent call last):
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
  File "G:\Python\lib\asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "G:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
  File "G:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "G:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "G:\Python\lib\asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dgram\base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 303, in processResponseVarBinds
    varBindTable, cbCtx):
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 345, in __cbFun
    varBindTable],
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 344, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 847, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 450, in resolveWithMib
    self.__indices = rowNode.getIndicesFromInstId(suffix)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\mibs\SNMPv2-SMI.py", line 1258, in getIndicesFromInstId
    (self, instId)
pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/CIS-Guest/PycharmProjects/AMIT_Automation/SNMP_V1/test_walk.py", line 24, in <module>
    ObjectType(ObjectIdentity('AMIT-PDU-MIB', 'pdu')),lookupMib=True,ignoreNonIncreasingOid=True
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\sync\cmdgen.py", line 362, in nextCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "G:\Python\lib\asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "G:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
;  File "G:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
;  File "G:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
;  File "G:\Python\lib\asyncore.py", line 422, in handle_read_event
    self.handle_read()
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dgram\base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 303, in processResponseVarBinds
    varBindTable, cbCtx):
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 345, in __cbFun
    varBindTable],
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 344, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 847, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 450, in resolveWithMib
    self.__indices = rowNode.getIndicesFromInstId(suffix)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\mibs\SNMPv2-SMI.py", line 1258, in getIndicesFromInstId
    (self, instId)
;pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1
caused by <class 'pysnmp.smi.error.SmiError'>: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1

_Originally posted by @cissuppandi in https://github.com/etingof/pysnmp/issues/6#issuecomment-490417998_

**Comment by lextm** [comment]
It seems that you raised two issues, this one as well as [this](https://github.com/etingof/pysnmp/issues/6#issuecomment-503061528).

It requires a lot more details (which SNMP agent you use, how the MIB document looks like, and the Python code you write).

I know you might have shared with Ilya, but he passed away without leaving any hint on his analysis. So, if you want them to be investigated again, you might send the necessary data to us via support@lextudio.com.
