### ISSUE TITLE
TypeError: resolveWithMib() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by mr-sven** [etingof/pysnmp#302]
Hi,
with the current release 4.4.11 I faced an issue with adding varbinds to a NotificationType:
```python
    oid = ObjectIdentity('TEST-MIB', 'testNotification').addMibSource(os.path.dirname(os.path.realpath(__file__)))

    # failing request    
    sendNotification(
        snmpEngine,
        CommunityData('public'),
        UdpTransportTarget(('localhost', 162)),
        ContextData(),
        'trap',
        NotificationType(oid).addVarBinds(
             ObjectType(ObjectIdentity('TEST-MIB', 'testName'), 'system name')
        )
    )
```
```bash
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    ObjectType(ObjectIdentity('TEST-MIB', 'testName'), 'system name')
  File "/usr/local/lib/python3.6/dist-packages/pysnmp/hlapi/asyncore/ntforg.py", line 139, in sendNotification
    vbProcessor.makeVarBinds(snmpEngine, varBinds),
  File "/usr/local/lib/python3.6/dist-packages/pysnmp/hlapi/varbinds.py", line 57, in makeVarBinds
    mibViewController, ignoreErrors=False)
  File "/usr/local/lib/python3.6/dist-packages/pysnmp/smi/rfc1902.py", line 1179, in resolveWithMib
    mibViewController, ignoreErrors)
TypeError: resolveWithMib() takes 2 positional arguments but 3 were given
```

I've seen the issue looks fixed in the master branch.
Package with test files: [test-script.zip](https://github.com/etingof/pysnmp/files/3535240/test-script.zip)

**Comment by GitGaryHuang** [comment]
I have met the same question when trying to send a trap.
I wonder if you have solve the problem?

**Comment by dramasamy** [comment]
Looks like the v4.4.10 introduced a bug. 

v4.4.9 works fine.

pip install pysnmp==4.4.9

`
>>> errorIndication, errorStatus, errorIndex, varBinds = next(
...     sendNotification(
...         SnmpEngine(),
...         CommunityData('public'),
...         UdpTransportTarget(('localhost', 162)),
...         ContextData(),
...         'trap',
...         NotificationType(
...             ObjectIdentity('IF-MIB', 'linkUp'),
...                            instanceIndex=(123,),
...                            objects={('IF-MIB', 'ifIndex'): 123,
...                                     ('IF-MIB', 'ifAdminStatus'): 'up',
...                                     ('IF-MIB', 'ifOperStatus'): 'up'}
...         )
...     )
... )
14:46:27.647865 IP (tos 0x0, ttl 64, id 47322, offset 0, flags [DF], proto UDP (17), length 148)
    localhost.localdomain.45928 > localhost.localdomain.snmptrap: [bad udp cksum 0xfe93 -> 0xe307!]  { SNMPv2c { V2Trap(105) R=12212467  system.sysUpTime.0=0 S:1.1.4.1.0=S:1.1.5.4 interfaces.ifTable.ifEntry.ifIndex.123=123 interfaces.ifTable.ifEntry.ifAdminStatus.123=1 interfaces.ifTable.ifEntry.ifOperStatus.123=1 } } 
>>> 
`

**Comment by batkins61** [comment]
I need the ability to pass in localized auth and priv keys in UsmUserData, so I need 4.4.11+.  I see the new ignoreErrors parameter added to all resolveWithMib definitions EXCEPT ObjectIdentity, which appears to be an oversight(?).

Is there a work around?

Example Code:
```
snmpEngine = SnmpEngine()
mibBuilder = snmpEngine.getMibBuilder()
mibBuilder.addMibSources(builder.DirMibSource('/usr/local/product/mibs'))
mibBuilder.loadModules('SNMPv2-MIB', 'NEW-MIB')
DateAndTime = mibBuilder.importSymbols('SNMPv2-TC', 'DateAndTime')[0]
mibView = view.MibViewController(mibBuilder)

errorIndication, errorStatus, errorIndex, varBinds = next(
    sendNotification(
        SnmpEngine(),
        UsmUserData('user1', 'authpass', 'privpass',
                    authProtocol=usmHMACSHAAuthProtocol,
                    privProtocol=usmAesCfb128Protocol),
        UdpTransportTarget(('10.10.10.161', 162)),
        ContextData(),
        'inform',
        NotificationType(
            ObjectIdentity('NEW-MIB', 'majorEvent'),
            objects={
                ('NEW-MIB', 'sourceId'): 12345678,
                ('NEW-MIB', 'attrCode'): 'PNOM',
            }
        ).resolveWithMib(mibView)
    )
)
```

```
Traceback (most recent call last):
  File "trap3.py", line 52, in <module>
    ).resolveWithMib(mibView)
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/rfc1902.py", line 1179, in resolveWithMib
    mibViewController, ignoreErrors)
TypeError: resolveWithMib() takes exactly 2 arguments (3 given)
```

**Comment by dramasamy** [comment]
> I need the ability to pass in localized auth and priv keys in UsmUserData, so I need 4.4.11+. I see the new ignoreErrors parameter added to all resolveWithMib definitions EXCEPT ObjectIdentity, which appears to be an oversight(?).
> 
> Is there a work around?
> 
> Example Code:
> 
> ```
> snmpEngine = SnmpEngine()
> mibBuilder = snmpEngine.getMibBuilder()
> mibBuilder.addMibSources(builder.DirMibSource('/usr/local/product/mibs'))
> mibBuilder.loadModules('SNMPv2-MIB', 'NEW-MIB')
> DateAndTime = mibBuilder.importSymbols('SNMPv2-TC', 'DateAndTime')[0]
> mibView = view.MibViewController(mibBuilder)
> 
> errorIndication, errorStatus, errorIndex, varBinds = next(
>     sendNotification(
>         SnmpEngine(),
>         UsmUserData('user1', 'authpass', 'privpass',
>                     authProtocol=usmHMACSHAAuthProtocol,
>                     privProtocol=usmAesCfb128Protocol),
>         UdpTransportTarget(('10.10.10.161', 162)),
>         ContextData(),
>         'inform',
>         NotificationType(
>             ObjectIdentity('NEW-MIB', 'majorEvent'),
>             objects={
>                 ('NEW-MIB', 'sourceId'): 12345678,
>                 ('NEW-MIB', 'attrCode'): 'PNOM',
>             }
>         ).resolveWithMib(mibView)
>     )
> )
> ```
> 
> ```
> Traceback (most recent call last):
>   File "trap3.py", line 52, in <module>
>     ).resolveWithMib(mibView)
>   File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/rfc1902.py", line 1179, in resolveWithMib
>     mibViewController, ignoreErrors)
> TypeError: resolveWithMib() takes exactly 2 arguments (3 given)
> ```

Did you try v4.4.9 ?

**Comment by batkins61** [comment]
4.9.9 does not have the ability to create UsmUserData with master or localized keys; only passphrases (q.v. UsmUserData.__init__ in auth.py under 4.4.9).   This is an automated process dispatching SNMPv3 notifications, so I need to pass in localized keys because I don't want to store pass phrases entered by a user.

**Comment by etingof** [comment]
> I've seen the issue looks fixed in the master branch.

I am curious if you could point out which commits fixies this...?

Meanwhile, let me reproduce this issue.

**Comment by Harm133** [comment]
Any updates on this issue?

**Comment by eminjin** [comment]
I met the same issue when I try to resolve my own smi mib.
It looks like in pysnmp/smi/rfc1902.py, class ObjectIdentity function resolveWithMib has no ignoreErrors parameter. Simply add ignoreErrors parameter in function definition entry can solve this problem. Introduced by commit e8fa40167, as commented: https://github.com/etingof/pysnmp/commit/e8fa401677432e4e48d1a9c36b996ef94b043d90#r38017455

**Comment by etingof** [comment]
Hey, sorry for this silly bug. I believe it has been fixed already, no?

**Comment by asoc** [comment]
Looks like you missed one spot in `ObjectIdentity`, around line 320. 

```python
  def resolveWithMib(self, mibViewController):
```

Should have the `ignoreErrors=True` arg as well.

**Comment by eminjin** [comment]
> 
> 
> Hey, sorry for this silly bug. I believe it has been fixed already, no?

It looks like there're 2 commits, https://github.com/etingof/pysnmp/commit/86790dd94886c743341f598533046f112ba6aea8 on master branch and https://github.com/etingof/pysnmp/commit/e8fa401677432e4e48d1a9c36b996ef94b043d90 on release branch created for the same topic, but different contents.

Now, the problem was not existed on master branch, but on release branch, it's still there.
On release branch "release-4.4.12", the code (line 1178) looks like:

>                 objectIdentity = ObjectIdentity(*notificationObject + self.__instanceIndex).resolveWithMib(
>                    mibViewController, ignoreErrors)

On master branch, the code (line 1305) looks like:
>                objectIdentity = ObjectIdentity(
>                    *notificationObject + self._instanceIndex)
>                objectIdentity.resolveWithMib(mibViewController)

**Comment by owford** [comment]
Hello,

I have the same problem while following the [documentation for "inform"](http://snmplabs.com/pysnmp/docs/pysnmp-hlapi-tutorial.html#sending-snmp-notifications).

I have :
Requirement already satisfied: pysnmp in ./.venv/lib/python3.5/site-packages (**4.4.12**)
Requirement already satisfied: pysmi in ./.venv/lib/python3.5/site-packages (from pysnmp) (0.3.4)
Requirement already satisfied: pycryptodomex in ./.venv/lib/python3.5/site-packages (from pysnmp) (3.9.8)
Requirement already satisfied: pyasn1>=0.2.3 in ./.venv/lib/python3.5/site-packages (from pysnmp) (0.4.8)
Requirement already satisfied: ply in ./.venv/lib/python3.5/site-packages (from pysmi->pysnmp) (3.11)

```
./.venv/bin/python3.5 
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysnmp.hlapi import *
>>> g = sendNotification(SnmpEngine(),
... CommunityData('public'),
... UdpTransportTarget(('demo.snmplabs.com', 162)),
... ContextData(),
... 'inform',
... NotificationType(ObjectIdentity('IF-MIB', 'linkUp'), instanceIndex=(123,))
... )
>>> next(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/..../.venv/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/sync/ntforg.py", line 118, in sendNotification
    lookupMib=options.get('lookupMib', True))
  File "/..../.venv/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/ntforg.py", line 139, in sendNotification
    vbProcessor.makeVarBinds(snmpEngine, varBinds),
  File "/..../.venv/lib/python3.5/site-packages/pysnmp/hlapi/varbinds.py", line 57, in makeVarBinds
    mibViewController, ignoreErrors=False)
  File "/..../.venv/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 1179, in resolveWithMib
    mibViewController, ignoreErrors)
TypeError: resolveWithMib() takes 2 positional arguments but 3 were given
```

I noticed 2 mentions of ignoreErrors in makeVarBinds() which may be fine (?) and 3 in resolveWithMib().

**Comment by straker741** [comment]
Hello, I have version **4.4.12** and stumbled across this bug too. I tried to send custom MIB:
```python
NotificationType(
  ObjectIdentity(
    'TEST-MIB', 'testNotificationTrap'
  ).addMibSource(
    '/home/pi/test'
  ),
  objects={
    ('TEST-MIB', 'testValue'): OctetString('100.0')
  }
)
```

I have resolved the error: _**TypeError:** resolveWithMib() takes 2 positional arguments but 3 were given_ by adding one more parameter to the method at the **row 306** in file **rtc1902.py** usually located in the folder _~/.local/lib/python3.7/site-packages/pysnmp/smi_. In my case the row 306 looks like this:
```python
def resolveWithMib(self, mibViewController, ignoreErrors=True):
```

I don't know what is the purpose of this addition but I assume it just doesn't display possible errors on the console?

Hope this helps someone. I hope Ilya will be able to rejoin us very soon. Take care.
