### ISSUE TITLE
No suitable module found : 'CISCO-CONFIG-COPY-MIB'

### ISSUE THREAD

**Issue by ljy296566** [etingof/pysnmp#309]
I want to use `pysnmp` to execute `snmp` command 
`snmpset -c public -v 2c 192.168.1.1 1.3.6.1.4.1.9.9.96.1.1.1.1.2.336 i 1`, 

where `1.3.6.1.4.1.9.9.96.1.1.1.1.2` is OID of `ccCopyProtocol` in `CISCO-CONFIG-COPY-MIB`. 
`336` is a random number.(Each time you copy to or from a device using SNMP, choose a random number. This number creates a row instance. It must be the same everywhere in your command.)

So I write this code:

```
g = setCmd(
    SnmpEngine(),
    CommunityData('public', mpModel=1),
    UdpTransportTarget(('192.168.1.1', 161)),
    ContextData(),
    ObjectType(ObjectIdentity('CISCO-CONFIG-COPY-MIB', 'ccCopyProtocol', 2), '1'))

next(g)
```

when I run this code, it report error:

```
No suitable module found : 'CISCO-CONFIG-COPY-MIB'
```

Could anyone help me deal with this error ?

furthermore, how can I implement the random number (`336`) in code?

**Comment by etingof** [comment]
Try [pointing pysnmp](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/mib-tweaks.html#custom-asn-1-mib-path) to a MIB repository so it will download the MIB(s) and use them:

```
ObjectType(
    ObjectIdentity('IF-MIB', 'ifInOctets', 1).addAsn1MibSource(
        'file:///usr/share/snmp',
        'http://mibs.snmplabs.com/asn1/@mib@')
    )
)
```

**Comment by ljy296566** [comment]
> Try [pointing pysnmp](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/mib-tweaks.html#custom-asn-1-mib-path) to a MIB repository so it will download the MIB(s) and use them:
> 
> ```
> ObjectType(
>     ObjectIdentity('IF-MIB', 'ifInOctets', 1).addAsn1MibSource(
>         'file:///usr/share/snmp',
>         'http://mibs.snmplabs.com/asn1/@mib@')
>     )
> )
> ```

Thank you for your reply. I tried it but it didn't work. 
this is my code:
```
errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           CommunityData('public'),
           UdpTransportTarget(('192.168.1.1', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('CISCO-CONFIG-COPY-MIB', 'ccCopyProtocol',0).
                               addAsn1MibSource(
                                 'file:///usr/share/snmp',
                                 'http://mibs.snmplabs.com/asn1/@mib@'))))
```
and it report error:
```
Traceback (most recent call last):
  File "custom-asn1-mib-search-path.py", line 25, in <module>
    ObjectType(ObjectIdentity('CISCO-CONFIG-COPY-MIB', 'ccCopyProtocol',0).addAsn1MibSource('file:///usr/share/snmp','http://mibs.snmplabs.com/asn1/@mib@'))
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 111, in getCmd
    lookupMib=options.get('lookupMib', True)))
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 130, in getCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds), __cbFun,
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/hlapi/varbinds.py", line 39, in makeVarBinds
    __varBinds.append(varBind.resolveWithMib(mibViewController, ignoreErrors=False))
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/rfc1902.py", line 853, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/rfc1902.py", line 510, in resolveWithMib
    self.__args[2:], mibNode.getLabel(), sys.exc_info()[1]))
pysnmp.smi.error.SmiError: Instance index (0,) to OID conversion failure at object 'ccCopyProtocol': <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 4294967295>, <ValueRangeConstraint object, consts 1, 2147483647>>  failed at: ValueConstraintError('<ValueRangeConstraint object, consts 1, 2147483647> failed at: ValueConstraintError(0,)',) at Unsigned32caused by <class 'pyasn1.type.error.ValueConstraintError'>: <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 4294967295>, <ValueRangeConstraint object, consts 1, 2147483647>> failed at: ValueConstraintError('<ValueRangeConstraint object, consts 1, 2147483647> failed at: ValueConstraintError(0,)',) at Unsigned32
```
what should I do now ?

**Comment by etingof** [comment]
Look at [the MIB](http://mibs.snmplabs.com/asn1/CISCO-CONFIG-COPY-MIB) - that table should not have `0` as an index. Try something in the range of 1..2147483647:

```
ccCopyIndex OBJECT-TYPE
    SYNTAX          Unsigned32 (1..2147483647 )
    MAX-ACCESS      not-accessible
    STATUS          current
    DESCRIPTION
        "Object which specifies a unique entry in the
        ccCopyTable.  A management station wishing
        to initiate a config-copy operation should use a
        random value for this object when creating
        or modifying an instance of a ccCopyEntry.
        The RowStatus semantics of the ccCopyEntryRowStatus
        object will prevent access conflicts." 
    ::= { ccCopyEntry 1 }

ccCopyProtocol OBJECT-TYPE
    SYNTAX          ConfigCopyProtocol
    MAX-ACCESS      read-create
    STATUS          current
    DESCRIPTION
        "The protocol to be used for any copy.

        If the copy operation occurs locally on the SNMP 
        agent (e.g. 'runningConfig' to 'startupConfig'),
        this object may be ignored by the implementation."
    DEFVAL          { tftp } 
    ::= { ccCopyEntry 2 }
```

**Comment by ljy296566** [comment]
The problem has been solved. Thank you for your help ! @etingof
