### ISSUE TITLE
Install pysnmp for 32 BIT target machine

### ISSUE THREAD

**Issue by shubham101096** [etingof/pysnmp#339]
On the 32 BIT target machine I am getting the following error when running the command:

>>> import pysnmp.hlapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pysnmp/hlapi/__init__.py", line 10, in <module>
    from pysnmp.hlapi import auth
  File "/usr/local/lib/python2.7/site-packages/pysnmp/hlapi/auth.py", line 7, in <module>
    from pysnmp.entity import config
  File "/usr/local/lib/python2.7/site-packages/pysnmp/entity/config.py", line 9, in <module>
    from pysnmp.proto.secmod.rfc3414.auth import hmacmd5, hmacsha, noauth
  File "/usr/local/lib/python2.7/site-packages/pysnmp/proto/secmod/rfc3414/__init__.py", line 7, in <module>
    from pysnmp.proto.secmod.rfc3414 import service
  File "/usr/local/lib/python2.7/site-packages/pysnmp/proto/secmod/rfc3414/service.py", line 11, in <module>
    from pysnmp.proto.secmod.rfc3414.priv import des, nopriv
  File "/usr/local/lib/python2.7/site-packages/pysnmp/proto/secmod/rfc3414/priv/des.py", line 17, in <module>
    from Cryptodome.Cipher import DES
  File "/usr/local/lib/python2.7/site-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 47, in <module>
    """
  File "/usr/local/lib/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 299, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.so': /usr/local/lib/python2.7.17/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.so: wrong ELF class: ELFCLASS64, Trying '_raw_ecbmodule.so': /usr/local/lib/python2.7.17/site-packages/Cryptodome/Util/../Cipher/_raw_ecbmodule.so: cannot open shared object file: No such file or directory

How to resolve this error or how to get 32 BIT version of pysnmp packages ?

**Comment by etingof** [comment]
That has something to do with the `pycryptodome` package. You should either remove it entirely (if you are not using strong SNMPv3 encryption) or pull the right binary version of it.

Alternatively, you can use pysnmp 5.x from GitHub master - it does not rigidly depend on `pycryptodome`.
