### ISSUE TITLE
Using Pysnmp with Multiprocessing or Threading

### ISSUE THREAD

**Issue by mohammedtalo** [etingof/pysnmp#340]

**Comment by mohammedtalo** [comment]
The error that I am getting is 



Getting OIDS for first device 192.168.122.6
Getting OIDS for first device 192.168.122.6
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "Threading.py", line 123, in Preditive_Assurance
    Node_name=get(ip, ['1.3.6.1.2.1.1.5.0'], hlapi.CommunityData('ICTSHORE'))
  File "Threading.py", line 17, in get
    return fetch(handler, 1)[0]
  File "Threading.py", line 48, in fetch
    error_indication, error_status, error_index, var_binds = next(handler)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 111, in getCmd
    lookupMib=options.get('lookupMib', True)))
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 130, in getCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds), __cbFun,
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/varbinds.py", line 39, in makeVarBinds
    __varBinds.append(varBind.resolveWithMib(mibViewController, ignoreErrors=False))
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/rfc1902.py", line 853, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/rfc1902.py", line 421, in resolveWithMib
    self.__oid
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/view.py", line 200, in getNodeNameByOid
    self.indexMib()
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/view.py", line 146, in indexMib
    mibMod['oidToLabelIdx'][oid] = oidToLabelIdx[oid]
KeyError: (1, 3, 6, 1, 4, 1, 20408)

         Name             IP   Port  ... Operation_Speed In_Error Utilization
0  AUH-7H2-ML  192.168.122.6  1/1/1  ...            1000        0        3236
1  AUH-7H2-ML  192.168.122.6  1/1/2  ...               0        0           0
2  AUH-7H2-ML  192.168.122.6  1/1/3  ...               0        0           0
3  AUH-7H2-ML  192.168.122.6  1/1/4  ...               0        0           0
4  AUH-7H2-ML  192.168.122.6  1/1/5  ...               0        0           0
5  AUH-7H2-ML  192.168.122.6    A/1  ...               0        0           0
6  AUH-7H2-ML  192.168.122.6    B/1  ...               0        0           0

[7 rows x 8 columns]

---- End get config threading, elapsed time= 1.1654002666473389
