### ISSUE TITLE
pysnmp error 

### ISSUE THREAD

**Issue by macka527** [etingof/pysnmp#370]
/media/flash/pysnmp # python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 179, in <module>
    setup(**params)
  File "/core.py", line 108, in setup
  File "/dist.py", line 267, in __init__
  File "/dist.py", line 1227, in set_requires
  File "/versionpredicate.py", line 114, in __init__
ValueError: expected parenthesized list: '>=(0.2.3)'

how to install? 
through pip there is no possibility: /
по русски говорите?

**Comment by lextm** [comment]
## Offline Install for pysnmp 7.x

### Using pip

The old setup.py install method no longer exists. pysnmp now uses pyproject.toml. Everything goes through pip.

- Step 1 — Download wheels on a machine with internet access
pysnmp has only one runtime dependency (pyasn1 >= 0.6.3), so you need two wheels:

  ```
  pip download pysnmp --dest ./offline_packages
  ```

  This downloads pysnmp and pyasn1 wheels into ./offline_packages/.

  If you need a specific version:

  ```
  pip download "pysnmp==7.1.27" --dest ./offline_packages
  ```

  If the target machine has a different OS/architecture (e.g., an embedded Linux device), specify the platform explicitly:

  ```
  pip download pysnmp \
    --dest ./offline_packages \
    --platform linux_aarch64 \
    --python-version 310 \
    --only-binary :all:
  ```

  Since both pysnmp and pyasn1 are pure-Python packages, the default wheels are universal and work on any platform/OS without needing --platform.

- Step 2 — Copy ./offline_packages/ to the target machine

  Transfer the directory via USB, SCP, or any other means.

- Step 3 — Install from the local directory

  ```
  pip install --no-index --find-links ./offline_packages pysnmp
  ```

  --no-index disables PyPI, --find-links points pip at your local wheel cache.

### Using Git

Installing from the git source (no internet on target)

If you want to install from the repository itself rather than PyPI:

```
# On internet-connected machine: clone and download deps
git clone https://github.com/lextudio/pysnmp.git
pip download pyasn1 --dest ./offline_packages   # only dependency
```
```
# Copy both the cloned repo and offline_packages to target, then:
pip install --no-index --find-links ./offline_packages ./pysnmp/
```
