### ISSUE TITLE
Crash using SNMPv3 and sha/aes with SmithSNMP server

### ISSUE THREAD

**Issue by grajus** [etingof/pysnmp#371]
PySNMP is crashing when using SNMPv3 and sha/aes with SmithSNMP server.

Test script:
```
#!/usr/bin/python

from pysnmp.hlapi import *

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           UsmUserData(userName='admin', authKey='88888888', privKey='88888888',
                       authProtocol=usmHMACSHAAuthProtocol,
                       privProtocol=usmAesCfb128Protocol),
           UdpTransportTarget(('192.168.50.156', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
)

if errorIndication:
    print(errorIndication)
elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
```

Crash dump:
```
Traceback (most recent call last):
  File "./testing.py", line 12, in <module>
    ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
  File "build/bdist.linux-x86_64/egg/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 113, in getCmd
  File "build/bdist.linux-x86_64/egg/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "build/bdist.linux-x86_64/egg/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
;  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
;  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
;  File "build/bdist.linux-x86_64/egg/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "build/bdist.linux-x86_64/egg/pysnmp/carrier/base.py", line 85, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "build/bdist.linux-x86_64/egg/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "build/bdist.linux-x86_64/egg/pysnmp/proto/rfc3412.py", line 344, in receiveMessage
    statusInformation
;  File "build/bdist.linux-x86_64/egg/pysnmp/proto/rfc3412.py", line 533, in __expireRequest
    cachedParams['cbCtx'])
;  File "build/bdist.linux-x86_64/egg/pysnmp/entity/rfc3413/cmdgen.py", line 74, in processResponsePdu
    errorIndication = statusInformation['errorIndication']
;  File "build/bdist.linux-x86_64/egg/pysnmp/proto/error.py", line 33, in __getitem__
    return self.__errorIndication[key]
;KeyError: 'errorIndication'
caused by <type 'exceptions.KeyError'>: 'errorIndication'
```

Tested on Ubuntu 18.04LTS (Python 2.7.17). Reproduces with master, also releases 4.4.13, 4.4.12.

SmithSNMP server acts in a non-standard way a bit by not putting OID 1.3.6.1.6.3.15.1.1.4.0 (usmStatsUnknownEngineID) in report PDU during engine ID dicovery. This makes PDU report to have an empty var-binds and as a consequence pysnmp code enterns this path in proto/mpmod/rfc3412.py:

```
else:
                statusInformation = error.StatusInformation(
                    sendPduHandle=sendPduHandle
                )
```

So, errorIndication is not present in this case, ergo the crash. I'm not very familiar with pysnmp code base, but a quick change would prevent this crash (for release-4.4.13 at least):

```
diff --git a/pysnmp/proto/mpmod/rfc3412.py b/pysnmp/proto/mpmod/rfc3412.py
index 7c4bec98..1ff68efe 100644
--- a/pysnmp/proto/mpmod/rfc3412.py
+++ b/pysnmp/proto/mpmod/rfc3412.py
@@ -658,6 +658,7 @@ class SnmpV3MessageProcessingModel(AbstractMessageProcessingModel):
                 )
             else:
                 statusInformation = error.StatusInformation(
+                    errorIndication=errind.reportPduReceived,
                     sendPduHandle=sendPduHandle
                 )
```

Maybe there is a better solution to prevent the crash in this situation.

**Comment by lextm** [comment]
The developers of SmithSNMP server should fix their own bugs in order to be compliant with SNMP standards, not the other way around.

**Comment by grajus** [comment]
> The developers of SmithSNMP server should fix their own bugs in order to be compliant with SNMP standards, not the other way around.

The library should not crash either way. It should handle invalid SNMP response without crashing.

**Comment by lextm** [comment]
@grajus That's impossible to achieve, because there are too many ways to violate the standards and a library like this cannot meaningfully catch all of them and handle reasonably. Throwing errors out is the simplest way and also gives you the freedom to catch and handle in your own code.

There were certain cases related to non-compliant agents reported in the past, and Ilya provided workarounds and documented in FAQ, such as "Ignored SNMP packets",

https://www.pysnmp.com/pysnmp/faq

However, your case is not.
