### ISSUE TITLE
why ValueConstraintValue data type is Integer32 not Gauge32 or Counter64?

### ISSUE THREAD

**Issue by Jasonjiang27** [etingof/pysnmp#384]

**Comment by Jasonjiang27** [comment]
@etingof   May you publish new version resolve this error？ thanks

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/usr/local/python3/lib/python3.7/site-packages/pyasn1/type/constraint.py", line 697, in _testValue
    constraint(value, idx)
  File "/usr/local/python3/lib/python3.7/site-packages/pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ValueRangeConstraint object, consts -2147483648, 2147483647> failed at: ValueConstraintError(2871697336)
