### ISSUE TITLE
TypeError in pysnmp/proto/api/v1.py with pyasn1==0.2.3

### ISSUE THREAD

**Issue by bennettp123** [etingof/pysnmp#40]
```
$ cat reproduce.py
#!/usr/bin/env python

from pysnmp.hlapi import *

ip = '<REDACTED>'
community = '<REDACTED>'

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           CommunityData(community, mpModel=0),
           UdpTransportTarget((ip, 161)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysName', 0).addAsn1MibSource('file:///usr/share/mibs/iana','file:///usr/share/mibs/ietf'))))
```

```
$ python reproduce.py
Traceback (most recent call last):
  File "reproduce.py", line 13, in <module>
    ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysName', 0).addAsn1MibSource('file:///usr/share/mibs/iana','file:///usr/share/mibs/ietf'))))
  File "/usr/local/lib/python3.6/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 111, in getCmd
    lookupMib=options.get('lookupMib', True)))
  File "/usr/local/lib/python3.6/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 131, in getCmd
    options.get('cbFun'), options.get('cbCtx'))
  File "/usr/local/lib/python3.6/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 214, in sendVarBinds
    v2c.apiPDU.setVarBinds(reqPDU, varBinds)
  File "/usr/local/lib/python3.6/site-packages/pysnmp/proto/api/v1.py", line 136, in setVarBinds
    varBindList.getComponentByPosition(idx), varBind
  File "/usr/local/lib/python3.6/site-packages/pysnmp/proto/api/v1.py", line 43, in setOIDVal
    verifyConstraints=False)
TypeError: setComponentByType() got multiple values for argument 'verifyConstraints'
```

Python versions tested:
* Python 3.6.0
* Python 2.7.13

### Python 3 modules

```
$ pip freeze
lxml==3.7.3
mock==2.0.0
ntlm-auth==1.0.2
ordereddict==1.1
pbr==1.10.0
pika==0.10.0
ply==3.10
pyasn1==0.2.3
pycryptodome==3.4.5
pysmi==0.0.7
pysnmp==4.3.3
python-logstash==0.4.6
requests==2.13.0
requests-ntlm==1.0.0
six==1.10.0
suds-jurko==0.6
```

### Python 2 modules

(slightly different)

```
$ pip freeze
appdirs==1.4.0
ftntlib==0.3.3
funcsigs==1.0.2
ipaddress==1.0.18
lxml==3.7.3
mock==2.0.0
ntlm-auth==1.0.2
ordereddict==1.1
packaging==16.8
pbr==1.10.0
pika==0.10.0
ply==3.10
pyasn1==0.2.3
pyciapi==0.2
pycryptodome==3.4.5
pyparsing==2.1.10
pysmi==0.0.7
pysnmp==4.3.3
python-logstash==0.4.6
requests==2.13.0
requests-ntlm==1.0.0
six==1.10.0
suds-jurko==0.6
virtualenv==15.1.0
```

This can worked around by downgrading to `pyasn1==0.2.2`.

**Comment by bennettp123** [comment]
Apologies; looks like it's already fixed.

Better fix: install `pysnmp==4.3.4` via `pip install git+https://github.com/etingof/pysnmp.git`

**Comment by etingof** [comment]
Thank you for your report and sorry for a silly bug! ;-)

The pyasn1 library is being in active development lately, so some adjustments in pysnmp part (which bases on pyasn1) is sometimes required.

If you go with option 2, that might trigger the latest pyasn1 master download as a dependency.

I will try to release pysnmp master within a week.

**Comment by etingof** [comment]
Version [4.3.4](https://github.com/etingof/pysnmp/releases/tag/v.4.3.4) has been released on PyPI. That should hopefully fix all the linked issues.

If not, please raise an issue with pysnmp and we will address that swiftly!

**Comment by baloo** [comment]
well it now conflicts with pyasn1=0.2.2 :) but nevermind.

**Comment by etingof** [comment]
This is how `pip install pysnmp --upgrade` works for me:

```
Installing collected packages: pyasn1, pysnmp
  Found existing installation: pyasn1 0.2.2
    Uninstalling pyasn1-0.2.2:
      Successfully uninstalled pyasn1-0.2.2
  Found existing installation: pysnmp 4.3.3
    Uninstalling pysnmp-4.3.3:
      Successfully uninstalled pysnmp-4.3.3
Successfully installed pyasn1-0.2.3 pysnmp-4.3.4
```

The pyasn1 dependency has been bumped. So I'm not sure what do you mean by "conflicts" here. ;-)

**Comment by baloo** [comment]
I fixed pdns tests so it looked like:
```
pysnmp>=4.3.2
pyasn1==0.2.2
```

Which installed:
```
pysnmp==4.3.4
pyasn1==0.2.2
```

Not sure how this is possible considering that `pysnmp` now depends on `pyasn1>=0.2.3`. 

Like I said, nevermind, I fixed the tests again and it's all good now :)

**Comment by MatthewHink** [comment]
Thank you all - very nice set of work @etingof
