### ISSUE TITLE
i have a error in mycode:caused by <class 'IndexError'>: pop from empty list

### ISSUE THREAD

**Issue by rationa1** [etingof/pysnmp#417]
I am confused. I didn't do anything，But sometimes my code doesn't work

ERROR:conpot.protocols.snmp.conpot_cmdrsp:poll error: Traceback (most recent call last):
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib64/python3.6/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/usr/lib64/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/usr/lib64/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib64/python3.6/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/usr/lib64/python3.6/asyncore.py", line 442, in handle_write_event
    self.handle_write()
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 142, in handle_write
    outgoingMessage, transportAddress = self.__outQueue.pop()
;IndexError: pop from empty list
caused by <class 'IndexError'>: pop from empty list
2022-04-26 20:45:41,407 poll error: Traceback (most recent call last):
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib64/python3.6/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/usr/lib64/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/usr/lib64/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib64/python3.6/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/usr/lib64/python3.6/asyncore.py", line 442, in handle_write_event
    self.handle_write()
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 142, in handle_write
    outgoingMessage, transportAddress = self.__outQueue.pop()
;IndexError: pop from empty list
caused by <class 'IndexError'>: pop from empty list
2022-04-26 20:45:41,409 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
  File "/usr/lib64/python3.6/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
  File "/usr/lib64/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib64/python3.6/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
  File "/usr/lib64/python3.6/asyncore.py", line 442, in handle_write_event
    self.handle_write()
  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 142, in handle_write
    outgoingMessage, transportAddress = self.__outQueue.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../conpot/protocols/snmp/conpot_cmdrsp.py", line 170, in handleMgmtOperation
    rspVarBinds = self.proxy.getRequest(snmp_version, oid, **user_info)
  File "../conpot/protocols/snmp/snmp_proxy.py", line 65, in getRequest
    ObjectIdentity(*args)
  File "/usr/local/lib/python3.6/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 183, in getCmd
    **kwargs):
  File "/usr/local/lib/python3.6/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 113, in getCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib64/python3.6/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/usr/lib64/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/usr/lib64/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib64/python3.6/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/usr/lib64/python3.6/asyncore.py", line 442, in handle_write_event
    self.handle_write()
;  File "/usr/local/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 142, in handle_write
    outgoingMessage, transportAddress = self.__outQueue.pop()
;IndexError: pop from empty list
caused by <class 'IndexError'>: pop from empty list

**Comment by rationa1** [comment]
I don't even know what went wrong, I hope to hear from you soon

**Comment by gmunumel** [comment]
Exactly same error for me. 

@rationa1, Do you manage to fix it?

**Comment by ericoschuch** [comment]
Old but there is no other reference on internet, so:

pyasn1: 0.4.8 => 0.5.0

pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
;TypeError: <lambda>() takes 3 positional arguments but 4 were given
caused by <class 'TypeError'>: <lambda>() takes 3 positional arguments but 4 were given

Solution: pip install pyasn1==0.4.8

**Comment by lextm** [comment]
@ericoschuch what you commented has nothing to do with the original issue.

**Comment by lextm** [comment]
Since asyncore and Python 3.6 are both considered deprecated, this isn't something anyone should spend more time on.

asyncio based API should be used instead.
