### ISSUE TITLE
Row consistency check failed for MibScalarInstance

### ISSUE THREAD

**Issue by LPiner** [etingof/pysnmp#50]
This started showing up about a day ago and I'm not having much luck with finding a solution.

``` 
02:01:00,437: WARNING/PoolWorker-1] 2017-03-27 02:01:00,437 pysnmp: getValue: returning RowStatus('active') for (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 8, 115, 54, 57, 56, 55, 49, 50, 51, 53, 57, 56, 54, 49, 57, 49, 52, 52, 53, 57, 50)
[2017-03-27 02:01:00,437: DEBUG/PoolWorker-1] getValue: returning RowStatus('active') for (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 8, 115, 54, 57, 56, 55, 49, 50, 51, 53, 57, 56, 54, 49, 57, 49, 52, 52, 53, 57, 50)
[2017-03-27 02:01:00,437: WARNING/PoolWorker-1] 2017-03-27 02:01:00,437 pysnmp: flipFlopFsm: fun <bound method MibTree.readGet of MibTree((1,), None)> suceeded for (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 8, 115, 54, 57, 56, 55, 49, 50, 51, 53, 57, 56, 54, 49, 57, 49, 52, 52, 53, 57, 50)='createAndGo'
[2017-03-27 02:01:00,437: DEBUG/PoolWorker-1] flipFlopFsm: fun <bound method MibTree.readGet of MibTree((1,), None)> suceeded for (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 8, 115, 54, 57, 56, 55, 49, 50, 51, 53, 57, 56, 54, 49, 57, 49, 52, 52, 53, 57, 50)='createAndGo'
[2017-03-27 02:01:00,437: WARNING/PoolWorker-1] 2017-03-27 02:01:00,437 pysnmp: flipFlopFsm: state readGet status ok -> fsmState stop
[2017-03-27 02:01:00,437: DEBUG/PoolWorker-1] flipFlopFsm: state readGet status ok -> fsmState stop
[2017-03-27 02:01:00,439: WARNING/PoolWorker-1] === Traceback ===
[2017-03-27 02:01:00,440: WARNING/PoolWorker-1] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/code/lpiner/python/tasks.py", line 168, in clear_line
    SNMP.clear_line_v2(hostname, port, line_number, community)
  File "/opt/code/lpiner/python/modules/snmp.py", line 35, in clear_line_v2
    result = next(g)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 217, in setCmd
    lookupMib=options.get('lookupMib', True)))
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 235, in setCmd
    addrName, paramsName = lcd.configure(snmpEngine, authData, transportTarget)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/hlapi/lcd.py", line 48, in configure
    authData.securityName
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/entity/config.py", line 88, in addV1System
    (snmpCommunityEntry.name + (8,) + tblIdx, 'createAndGo'))
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/instrum.py", line 256, in writeVars
    return self.flipFlopFsm(self.fsmWriteVar, varBinds, acInfo)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/instrum.py", line 242, in flipFlopFsm
    raise origExc.with_traceback(origTraceback)
  File "/usr/local/lib/python3.5/dist-packages/pysnmp/smi/instrum.py", line 221, in flipFlopFsm
    rval = f(tuple(name), val, idx, acInfo)
  File "<string>", line 502, in writeCommit
  File "<string>", line 1174, in writeCommit
pysnmp.smi.error.InconsistentValueError: InconsistentValueError({'msg': 'Row consistency check failed for MibScalarInstance((1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 2, 115, 54, 57, 56, 55, 49, 50, 51, 53, 57, 56, 54, 49, 57, 49, 52, 52, 53, 57, 50), OctetString())'})
```

Here is the calling code:
```
        g = setCmd(SnmpEngine(),
               CommunityData(community),
               UdpTransportTarget((hostname, 161)),
               ContextData(),
               ObjectType(ObjectIdentity('OLD-CISCO-TS-MIB', 'tsClrTtyLine', 0).addMibSource(Configuration().app_root + '/resources/MIBS'), int(line_number)))
        result = next(g)
```

And I won't post the compiled MIB unless needed but it here is the compilation info:
```
#
# PySNMP MIB module OLD-CISCO-TS-MIB (http://pysnmp.sf.net)
# ASN.1 source http://mibs.snmplabs.com:80/asn1/OLD-CISCO-TS-MIB
# Produced by pysmi-0.0.7 at Thu Mar  9 17:35:10 2017
# On host LPINER-M-V18L platform Darwin version 15.5.0 by user larkinpiner
# Using Python version 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
#
```

**Comment by etingof** [comment]
Thanks for reporting this issue!

Could you please specify your `pyasn1/pysnmp/pysmi` versions?

In general, that looks like a SNMPv1 configuration inconsistency. Make sure you are feeding it a non-empty `community`.

**Comment by LPiner** [comment]
Wow, nice catch. Some how I was feeding it a blank community.

Thanks for the fast response!
