### ISSUE TITLE
Error happened when dst IP is in the case: TTL expired

### ISSUE THREAD

**Issue by hanbaobao2005** [etingof/pysnmp#66]
Software Version:
Python3.4/3.3
ply (3.10)
pyasn1 (0.2.3)
pycrypto (2.6.1)
pycryptodome (3.4.6)
pysmi (0.1.3)
pysnmp (4.3.8)
Windows2008R2

Error happened when TTL expired:
Pinging 192.168.245.2 with 32 bytes of data:
Reply from 192.168.252.3: TTL expired in transit.
Reply from 192.168.252.3: TTL expired in transit.
Reply from 192.168.252.3: TTL expired in transit.
Reply from 192.168.252.3: TTL expired in transit.

Ping statistics for 192.168.245.2:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)

Error:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 155, in handle_read
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 38, in __recvfrom
OSError: [WinError 10052] The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
  File "C:\Python34\lib\asyncore.py", line 212, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 171, in handle_read
pysnmp.carrier.error.CarrierError: recvfrom() failed: [WinError 10052] The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Dropbox (NT)\multi-vendor support\Mimic Files\Scripts\SNMP.py", line 83, in <module>
    SNMP_set_hostname(dit[1], dit[0])
  File "C:\Users\Administrator\Dropbox (NT)\multi-vendor support\Mimic Files\Scripts\SNMP.py", line 33, in SNMP_set_hostname
    lookupValues=True
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\entity\rfc3413\oneliner\cmdgen.py", line 200, in setCmd
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\hlapi\asyncore\sync\cmdgen.py", line 219, in setCmd
  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dispatch.py", line 50, in runDispatcher
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 155, in handle_read
    incomingMessage, transportAddress = self._recvfrom(self.socket, 65535)
;  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 38, in __recvfrom
    d, a = s.recvfrom(sz)
;OSError: [WinError 10052] The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress
;
During handling of the above exception, another exception occurred:

;Traceback (most recent call last):
;  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "C:\Python34\lib\asyncore.py", line 212, in loop
    poll_fun(timeout, map)
;  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
;  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
;  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
;  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
;  File "C:\Python34\lib\site-packages\pysnmp-4.3.8-py3.4.egg\pysnmp\carrier\asyncore\dgram\base.py", line 171, in handle_read
    raise error.CarrierError('recvfrom() failed: %s' % (sys.exc_info()[1],))
;pysnmp.carrier.error.CarrierError: recvfrom() failed: [WinError 10052] The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress

**Comment by etingof** [comment]
That looks like a network problem to me... SNMP might be totally unrelated to this. I can imagine this kind of behaviour when you have a routing loop on your network, for example.
