### ISSUE TITLE
Twisted hlapi: MIB resolution SmiError not handled

### ISSUE THREAD

**Issue by nrolans** [etingof/pysnmp#9]
Some exceptions from the callback functions `__cbFun` are not handled.

Here is an exception happening during a MIB lookup with a value that does not satisfy a constraint.

```
Unhandled Error
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    reactor.run()
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/carrier/base.py", line 68, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/entity/engine.py", line 145, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/proto/rfc3412.py", line 458, in receiveMessage
    cachedParams['cbCtx'])
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 131, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 355, in processResponseVarBinds
    varBindTable, cbCtx):
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/hlapi/twisted/cmdgen.py", line 477, in __cbFun
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in varBindTable])
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/hlapi/varbinds.py", line 43, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "/home/nrolans/.venvs/blah/lib/python2.7/site-packages/pysnmp/smi/rfc1902.py", line 859, in resolveWithMib
    raise SmiError('MIB object %r having type %r failed to cast value %r: %s' % (self.__args[0].prettyPrint(), self.__args[0].getMibNode().getSyntax().__class__.__name__, self.__args[1], sys.exc_info()[1]))
pysnmp.smi.error.SmiError: MIB object 'BGP4-MIB::bgp4PathAttrASPathSegment.10.2.3.0.24.10.20.20.20' having type 'OctetString' failed to cast value OctetString(''): ConstraintsIntersection(ConstraintsIntersection(ConstraintsIntersection(), ValueSizeConstraint(0, 65535)), ValueSizeConstraint(2, 255)) failed at: "ValueSizeConstraint(2, 255) failed at: """ at OctetString
```

I currently work around this by catching all exceptions in `__cbFun` and calling the error callback like this.

```
    def __cbFun(snmpEngine, sendRequestHandle,
                errorIndication, errorStatus, errorIndex,
                varBindTable, cbCtx):
        try:
            lookupMib, deferred = cbCtx
            if errorIndication:
                deferred.errback(Failure(errorIndication))
            else:
                    deferred.callback(
                        (errorStatus, errorIndex,
                            [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in varBindTable])
                    )
        except Exception as e:
            deferred.errback(Failure(e))
```

I'm happy to send a pull request with this or try another approach if you can give some direction.

I'm running Python 2.7.8 and these module versions
```
Twisted==16.2.0
pyasn1==0.1.9
pycrypto==2.6.1
pysmi==0.0.7
pysnmp==4.3.2
```

Thanks!

**Comment by etingof** [comment]
It does not look like a pysnmp problem. Rather it is malformed data coming from your SNMP Agent. According to MIB definition, `BGP4-MIB::bgp4PathAttrASPathSegment` object should have length between 2 and 255 octets while the value you receive has length zero.

However I'm planning to introduce an option to pysnmp hlapi to make it ignoring constraints violations like this one. If you case spare cycles to work on such feature - I'd appreciate it. ;-)

**Comment by sbraz** [comment]
Hi @etingof, is there any chance to see this feature added (ignoring size constraints)?

**Comment by etingof** [comment]
Most certainly! I'm just a bit overwhelmed atm. But it's on my plate!

**Comment by lextm** [comment]
Since this is caused by agent bugs, not going to work on it in future PySNMP releases. Close it now.
